service: orders
frameworkVersion: 4.4.x

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2

  # Lambda Configs
  memorySize: 512
  architecture: arm64

  # Logs Configs
  logRetentionInDays: 7

  # IAM role

# Environment Variables
environment:

# Resources
resources:
  Resources:
  Output:

# Functions
functions: