services:
  shared-cognito:
    path: src/shared-infrastructure/cognito
    params:
      AWS_REGION: ${env:AWS_REGION}
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
  shared-apigateway:
    path: src/shared-infrastructure/apigateway
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      COGNITO_ISSUER_URL: ${shared-cognito.CognitoIssuerUrl}
      COGNITO_AUDIENCE: ${shared-cognito.CognitoAudience}
  auth:
    path: src/modules/auth
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      ROOT_APIGATEWAY: ${shared-apigateway.ApiId}
      COGNITO_USER_POOL_ARN: ${shared-cognito.CognitoUserPoolArn}
      COGNITO_USER_POOL_ID: ${shared-cognito.CognitoUserPoolId}
      COGNITO_USER_POOL_CLIENT_ID: ${shared-cognito.CognitoUserPoolClientId}
  users:
    path: src/modules/users
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      ROOT_APIGATEWAY: ${shared-apigateway.ApiId}
      SAVE_AUTH_USER_FUNCTION: ${auth.SaveAuthUserFunction}
      SAVE_AUTH_USER_FUNCTION_ARN: ${auth.SaveAuthUserFunctionArn}
  orders:
    path: src/modules/orders
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      ROOT_APIGATEWAY: ${shared-apigateway.ApiId}
      COGNITO_ISSUER_URL: ${shared-cognito.CognitoIssuerUrl}
      COGNITO_AUDIENCE: ${shared-cognito.CognitoAudience}
      COGNITO_AUTHORIZER_ID: ${shared-apigateway.CognitoAuthorizerId}
