services:
  shared-apigateway:
    path: src/shared-infrastructure/apigateway
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
  auth:
    path: src/modules/auth
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      ROOT_APIGATEWAY: ${shared-apigateway.ApiId}
  users:
    path: src/modules/users
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      ROOT_APIGATEWAY: ${shared-apigateway.ApiId}
      SAVE_AUTH_USER_FUNCTION: ${auth.SAVE_AUTH_USER_FUNCTION}
      SAVE_AUTH_USER_FUNCTION_ARN: ${auth.SAVE_AUTH_USER_FUNCTION_ARN}
  orders:
    path: src/modules/orders
    params:
      DEPLOY_CF_ROLE: ${env:DEPLOY_CF_ROLE}
      AWS_REGION: ${env:AWS_REGION}
      ROOT_APIGATEWAY: ${shared-apigateway.ApiId}
