service: users
frameworkVersion: 4.4.x

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2

  # Lambda Configs
  memorySize: 512
  architecture: arm64

  # Logs Configs
  logRetentionInDays: 1
enviorment:
  COGNITO_CLIENT_ID:
    Ref: UserPoolClient
  COGNITO_USER_POOL_ID:
    Ref: UserPool
resources:
  Resources:
    UserPool: 
      Type: AWS::Cognito::UserPool
      Properties:
        UserPoolName: ${self:service}-user-pool
        UsernameAttributes:
          - email
        AutoVerifiedAttributes:
          - email
        Policies:
          PasswordPolicy:
            MinimumLength: 6
            RequireLowercase: false
            RequireNumbers: false
            RequireSymbols: false
            RequireUppercase: false
        Schema:
          - Name: email
            Required: true
            AttributeDataType: String
            Mutable: true
          - Name: name
            Required: true
            AttributeDataType: String
            Mutable: true
          - Name: phone_number
            Required: true
            AttributeDataType: String
            Mutable: true
    UserGroupAdmin:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: ${self:service}-admin-group
        UserPoolId: !Ref UserPool
    UserGroupDriver:
      Type: AWS::Cognito::UserPoolGroup
      Properties:
        GroupName: ${self:service}-driver-group
        UserPoolId: !Ref UserPool    
    UserPoolClient:
      Type: AWS::Cognito::UserPoolClient
      Properties:
        ClientName: ${self:service}-user-pool-client
        UserPoolId: !Ref UserPool
        GenerateSecret: false
        ExplicitAuthFlows:
          - USER_PASSWORD_AUTH
functions:
    register:
      handler: src/handlers/register.handler

