service: auth
frameworkVersion: 4.4.x

provider:
  name: aws
  runtime: nodejs22.x
  region: us-east-2

  # Lambda Configs
  memorySize: 512
  architecture: arm64

  # Logs Configs
  logRetentionInDays: 7

  # Root API
  httpApi:
    id: ${param:ROOT_APIGATEWAY}

  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - cognito-idp:AdminInitiateAuth
            - cognito-idp:AdminCreateUser
            - cognito-idp:AdminSetUserPassword
            - cognito-idp:AdminUpdateUserAttributes
            - cognito-idp:AdminDeleteUser
          Resource:
            - ${param:COGNITO_USER_POOL_ARN}

  environment:
    COGNITO_USER_POOL_ID: ${param:COGNITO_USER_POOL_ID}
    COGNITO_CLIENT_ID: ${param:COGNITO_USER_POOL_CLIENT_ID}

functions:
  login:
    handler: exports/loginFunction.handle
    events:
      - httpApi:
          path: /auth/login
          method: POST

  refreshToken:
    handler: exports/refreshTokenFunction.handle
    events:
      - httpApi:
          path: /auth/refresh-token
          method: POST
  logout:
    handler: exports/logoutFunction.handle
    events:
      - httpApi:
          path: /auth/logout
          method: POST
  saveAuth:
    handler: exports/createAuth.handle

resources:
  Outputs:
    SaveAuthUserFunction:
      Value: !Ref SaveAuthLambdaFunction
    SaveAuthUserFunctionArn:
      Value: !GetAtt SaveAuthLambdaFunction.Arn
